export const ASSIGNMENT_CREATE_REQUEST = "ASSIGNMENT_CREATE_REQUEST";
export const ASSIGNMENT_CREATE_SUCCESS = "ASSIGNMENT_CREATE_SUCCESS";
export const ASSIGNMENT_CREATE_FAILS = "ASSIGNMENT_CREATE_FAILS";
