export const ONE_COURSE_DETAILS_REQUEST = "ONE_COURSE_DETAILS_REQUEST";
export const ONE_COURSE_DETAILS_SUCCESS = "ONE_COURSE_DETAILS_SUCCESS";
export const ONE_COURSE_DETAILS_FAILS = "ONE_COURSE_DETAILS_FAILS";

export const ALL_USER_COURSES_REQUEST = "ALL_USER_COURSES_REQUEST";
export const ALL_USER_COURSES_SUCCESS = "ALL_USER_COURSES_SUCCESS";
export const ALL_USER_COURSES_FAILS = "ALL_USER_COURSES_FAILS";

export const FRONTEND_COURSES__LIST_REQUEST = "FRONTEND_COURSES__LIST_REQUEST";
export const FRONTEND_COURSES__LIST_SUCCESS = "FRONTEND_COURSES__LIST_SUCCESS";
export const FRONTEND_COURSES__LIST_FAILS = "FRONTEND_COURSES__LIST_FAILS";

export const BACKEND_COURSES__LIST_REQUEST = "BACKEND_COURSES__LIST_REQUEST";
export const BACKEND_COURSES__LIST_SUCCESS = "BACKEND_COURSES__LIST_SUCCESS";
export const BACKEND_COURSES__LIST_FAILS = "BACKEND_COURSES__LIST_FAILS";

export const DESIGNING_COURSES__LIST_REQUEST =
  "DESIGNING_COURSES__LIST_REQUEST";
export const DESIGNING_COURSES__LIST_SUCCESS =
  "DESIGNING_COURSES__LIST_SUCCESS";
export const DESIGNING_COURSES__LIST_FAILS = "DESIGNING_COURSES__LIST_FAILS";

export const DATABASE_COURSES__LIST_REQUEST = "DATABASE_COURSES__LIST_REQUEST";
export const DATABASE_COURSES__LIST_SUCCESS = "DATABASE_COURSES__LIST_SUCCESS";
export const DATABASE_COURSES__LIST_FAILS = "DATABASE_COURSES__LIST_FAILS";

export const FULLSTACK_COURSES__LIST_REQUEST =
  "FULLSTACK_COURSES__LIST_REQUEST";
export const FULLSTACK_COURSES__LIST_SUCCESS =
  "FULLSTACK_COURSES__LIST_SUCCESS";
export const FULLSTACK_COURSES__LIST_FAILS = "FULLSTACK_COURSES__LIST_FAILS";

export const OTHER_COURSES_LIST_REQUEST = "OTHER_COURSES_LIST_REQUEST";
export const OTHER_COURSES_LIST_SUCCESS = "OTHER_COURSES_LIST_SUCCESS";
export const OTHER_COURSES_LIST_FAILS = "OTHER_COURSES_LIST_FAILS";

export const ALL_INSTRUCTOR_COURSES_REQUEST = "ALL_INSTRUCTOR_COURSES_REQUEST";
export const ALL_INSTRUCTOR_COURSES_SUCCESS = "ALL_INSTRUCTOR_COURSES_SUCCESS";
export const ALL_INSTRUCTOR_COURSES_FAILS = "ALL_INSTRUCTOR_COURSES_FAILS";

export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_CREATE_SUCCESS = "COURSE_CREATE_SUCCESS";
export const COURSE_CREATE_FAILS = "COURSE_CREATE_FAILS";
