export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILS = "USER_LOGIN_FAILS";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILS = "USER_REGISTER_FAILS";

export const IS_USER_ENROLLED_REQUEST = "IS_USER_ENROLLED_REQUEST";
export const IS_USER_ENROLLED_SUCCESS = "IS_USER_ENROLLED_SUCCESS";
export const IS_USER_ENROLLED_FAILS = "IS_USER_ENROLLED_FAILS";
export const IS_USER_ENROLLED_RESET = "IS_USER_ENROLLED_RESET";
